---
spring:
  application:
    name: spring-maven-template
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    web: debug

---
spring:
  profiles:
    default: local